# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20160223_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='uploads/images/'),
        ),
    ]
