# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20160224_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='uploads/dk_editor/images/'),
        ),
    ]
